name: Google Trending Data Scraper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: rm -rf ./data
    - run: mkdir data
    - run: npm install --if-present
    - run: npm start

    - name: Commit and push if it changed
      run: |-
        git config user.name "skiddle-bot"
        git config user.email "165562787+skiddle-bot@users.noreply.github.com"
        git add -A
        timestamp=$(date '+%F %H:%M:%S %Z')
        git commit -m "Update Data ${timestamp}" || exit 0
        git push

    - name: Notify via Discord (Success)
      if: success()
      run: |
        TIME=$(date +"%Y-%m-%d %H:%M:%S")
        curl -H "Content-Type: application/json" \
        -X POST -d "$(jq -n --arg repo "${{ github.repository }}" \
                           --arg branch "${{ github.ref_name }}" \
                           --arg workflow "${{ github.workflow }}" \
                           --arg time "$TIME" \
                           '{
          "embeds": [{
            "title": "✅ Google Trends Scrape Successful",
            "description": "Trending data was scraped and committed successfully.",
            "color": 3426654,
            "fields": [
              {"name": "Repository", "value": $repo, "inline": true},
              {"name": "Branch", "value": $branch, "inline": true},
              {"name": "Workflow", "value": $workflow, "inline": true},
              {"name": "Time", "value": $time}
            ],
            "footer": {"text": "Skiddle Bot | GitHub Actions"}
          }]
        }')" ${{ secrets.DISCORD_WEBHOOK }}
      shell: bash

    - name: Notify via Discord (Failure)
      if: failure()
      run: |
        TIME=$(date +"%Y-%m-%d %H:%M:%S")
        curl -H "Content-Type: application/json" \
        -X POST -d "$(jq -n --arg repo "${{ github.repository }}" \
                           --arg branch "${{ github.ref_name }}" \
                           --arg workflow "${{ github.workflow }}" \
                           --arg time "$TIME" \
                           '{
          "embeds": [{
            "title": "❌ Google Trends Scrape Failed",
            "description": "An error occurred while scraping trending data.",
            "color": 15158332,
            "fields": [
              {"name": "Repository", "value": $repo, "inline": true},
              {"name": "Branch", "value": $branch, "inline": true},
              {"name": "Workflow", "value": $workflow, "inline": true},
              {"name": "Time", "value": $time}
            ],
            "footer": {"text": "Skiddle Bot | GitHub Actions"}
          }]
        }')" ${{ secrets.DISCORD_WEBHOOK }}
      shell: bash
